### ISSUE TITLE
Blog title for a specified blog

### ISSUE THREAD

**Issue by qiukeren** [rosario/kasper#19]
kasper is very good;

however, 
for example,http://qiukeren.github.io/segmentfault/2015/05/01/welcome-to-jekyll.html
if it is better that set the page.title the same as post.title?

**Comment by qiukeke** [comment]
Oh, i modified the default.html as follows my self so it worked.
 `<title>{{page.title}} - {{ site.name }} - {{ site.description }}</title>`
