### ISSUE TITLE
Error "Invalid theme" when uploading to ghost

### ISSUE THREAD

**Issue by gschurck** [rosario/kasper#57]
I get this error when I upload the zip to Ghost
![image](https://user-images.githubusercontent.com/21091232/149954643-d28115bf-aedf-4282-8dd9-c1406496e133.png)

**Comment by BirbEXE** [comment]
this is a [jekyll](https://jekyllrb.com) theme, not a [ghost](https;//ghost.org) theme

**Comment by gschurck** [comment]
Oh okay thanks
